
# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
# On branch master
#
# Initial commit
#
# Changes to be committed:
#	new file:   .gitignore
#	new file:   README.md
#	new file:   app/.htaccess
#	new file:   app/AppCache.php
#	new file:   app/AppKernel.php
#	new file:   app/Resources/views/base.html.twig
#	new file:   app/Resources/views/default/index.html.twig
#	new file:   app/Resources/views/default/success.html.twig
#	new file:   app/SymfonyRequirements.php
#	new file:   app/autoload.php
#	new file:   app/cache/.gitkeep
#	new file:   app/check.php
#	new file:   app/config/config.yml
#	new file:   app/config/config_dev.yml
#	new file:   app/config/config_prod.yml
#	new file:   app/config/config_test.yml
#	new file:   app/config/parameters.yml.dist
#	new file:   app/config/routing.yml
#	new file:   app/config/routing_dev.yml
#	new file:   app/config/security.yml
#	new file:   app/config/services.yml
#	new file:   app/console
#	new file:   app/logs/.gitkeep
#	new file:   app/phpunit.xml.dist
#	new file:   composer.json
#	new file:   composer.lock
#	new file:   nbproject/private/private.properties
#	new file:   nbproject/private/private.xml
#	new file:   nbproject/project.properties
#	new file:   nbproject/project.xml
#	new file:   src/.htaccess
#	new file:   src/AppBundle/AppBundle.php
#	new file:   src/AppBundle/Controller/DefaultController.php
#	new file:   src/AppBundle/Entity/Category.php
#	new file:   src/AppBundle/Entity/Tag.php
#	new file:   src/AppBundle/Form/CategoryType.php
#	new file:   src/AppBundle/Form/TagType.php
#	new file:   src/AppBundle/Repository/CategoryRepository.php
#	new file:   src/AppBundle/Repository/TagRepository.php
#	new file:   src/AppBundle/Tests/Controller/DefaultControllerTest.php
#	new file:   web/.htaccess
#	new file:   web/Chosen/chosen-sprite.png
#	new file:   web/Chosen/chosen-sprite@2x.png
#	new file:   web/Chosen/chosen.css
#	new file:   web/Chosen/chosen.jquery.js
#	new file:   web/Chosen/chosen.jquery.min.js
#	new file:   web/Chosen/chosen.min.css
#	new file:   web/Chosen/chosen.proto.js
#	new file:   web/Chosen/chosen.proto.min.js
#	new file:   web/Chosen/docsupport/chosen.png
#	new file:   web/Chosen/docsupport/event.simulate.js
#	new file:   web/Chosen/docsupport/oss-credit.png
#	new file:   web/Chosen/docsupport/prism.css
#	new file:   web/Chosen/docsupport/prism.js
#	new file:   web/Chosen/docsupport/style.css
#	new file:   web/Chosen/index.html
#	new file:   web/Chosen/index.proto.html
#	new file:   web/Chosen/options.html
#	new file:   web/app.php
#	new file:   web/app_dev.php
#	new file:   web/apple-touch-icon.png
#	new file:   web/config.php
#	new file:   web/dist/css/select2.css
#	new file:   web/dist/css/select2.min.css
#	new file:   web/dist/js/i18n/ar.js
#	new file:   web/dist/js/i18n/az.js
#	new file:   web/dist/js/i18n/bg.js
#	new file:   web/dist/js/i18n/ca.js
#	new file:   web/dist/js/i18n/cs.js
#	new file:   web/dist/js/i18n/da.js
#	new file:   web/dist/js/i18n/de.js
#	new file:   web/dist/js/i18n/el.js
#	new file:   web/dist/js/i18n/en.js
#	new file:   web/dist/js/i18n/es.js
#	new file:   web/dist/js/i18n/et.js
#	new file:   web/dist/js/i18n/eu.js
#	new file:   web/dist/js/i18n/fa.js
#	new file:   web/dist/js/i18n/fi.js
#	new file:   web/dist/js/i18n/fr.js
#	new file:   web/dist/js/i18n/gl.js
#	new file:   web/dist/js/i18n/he.js
#	new file:   web/dist/js/i18n/hi.js
#	new file:   web/dist/js/i18n/hr.js
#	new file:   web/dist/js/i18n/hu.js
#	new file:   web/dist/js/i18n/id.js
#	new file:   web/dist/js/i18n/is.js
#	new file:   web/dist/js/i18n/it.js
#	new file:   web/dist/js/i18n/ja.js
#	new file:   web/dist/js/i18n/km.js
#	new file:   web/dist/js/i18n/ko.js
#	new file:   web/dist/js/i18n/lt.js
#	new file:   web/dist/js/i18n/lv.js
#	new file:   web/dist/js/i18n/mk.js
#	new file:   web/dist/js/i18n/ms.js
#	new file:   web/dist/js/i18n/nb.js
#	new file:   web/dist/js/i18n/nl.js
#	new file:   web/dist/js/i18n/pl.js
#	new file:   web/dist/js/i18n/pt-BR.js
#	new file:   web/dist/js/i18n/pt.js
#	new file:   web/dist/js/i18n/ro.js
#	new file:   web/dist/js/i18n/ru.js
#	new file:   web/dist/js/i18n/sk.js
#	new file:   web/dist/js/i18n/sr-Cyrl.js
#	new file:   web/dist/js/i18n/sr.js
#	new file:   web/dist/js/i18n/sv.js
#	new file:   web/dist/js/i18n/th.js
#	new file:   web/dist/js/i18n/tr.js
#	new file:   web/dist/js/i18n/uk.js
#	new file:   web/dist/js/i18n/vi.js
#	new file:   web/dist/js/i18n/zh-CN.js
#	new file:   web/dist/js/i18n/zh-TW.js
#	new file:   web/dist/js/select2.full.js
#	new file:   web/dist/js/select2.full.min.js
#	new file:   web/dist/js/select2.js
#	new file:   web/dist/js/select2.min.js
#	new file:   web/favicon.ico
#	new file:   web/robots.txt
#
